name: Update AdBlock Auto
on:
  push:
    branches: [ master ]
  schedule: 
    - cron:  '0 0 */1 * *' 

jobs:
  update-adblock-rules-then-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.0.0
            
      - name: Adguard Simplified Domain Names Filter
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
          file-name: AdGuard_Simplified_Domain_Names_Filter.txt

      - name: EasyList China
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://easylist-downloads.adblockplus.org/easylistchina.txt
          file-name: Easylist_China.txt

      - name: EasyList Privacy
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://easylist.to/easylist/easyprivacy.txt
          file-name: Easylist_Privacy.txt
      
      - name: I dont care about cookies
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://www.i-dont-care-about-cookies.eu/abp/
          file-name: I_dont_care_about_cookies.txt      
      
      - name: HalfLife
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt
          file-name: HalfLife.txt  
          
      - name: CJX's EasyList Lite
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt
          file-name: CJX's_EasyList_Lite.txt  
          
      - name: CJX's Annoyance List
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          file-name: CJX's_Annoyance_List.txt  
          
      - name: 乘风广告过滤
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://gitee.com/xinggsf/Adblock-Rule/raw/master/rule.txt
          file-name: xinggsf_rule.txt

      - name: 乘风视频过滤
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://gitee.com/xinggsf/Adblock-Rule/raw/master/mv.txt
          file-name: chenfeng_mv.txt

      - name: Commit Changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
              exit 0
            else 
              git add .
              git config --local user.email "auto@zju.edu.cn"
              git config --local user.name "Auto"
              git commit -m "Updated at $(date)" -a
            fi
            
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.TOKEN }}
          
      - name: WeChat notification
        run: curl https://sc.ftqq.com/${{ secrets.ServerChan }}.send?text=${{ env.FILE_NAME }}今日规则已更新-GitHub Actions运行结束
